### ISSUE TITLE
Rule to avoid unassigned array.map

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/eslint-config-cheminfo-typescript#25]
Could we add a rule that prevents 

array.map( () => {})

A .map should always be assigned to a variable and this would prevent:

https://github.com/mljs/spectra-fitting/blob/c84f47fcc70570ceec524ced42aa6ee25d64c584/src/__tests__/optimize.test.ts#L179

In a similar way `array.forEach` should not be assigned to a variable.

**Comment by targos** [comment]
moved to the typescript config because this kind of rules requires type information.

**Comment by targos** [comment]
I think this is close to impossible to do ourselves. See https://github.com/eslint/eslint/issues/12980
You can reopen if a plugin or something already exists for that use case.
