### ISSUE TITLE
Not fan of prefer-regexp-exec

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/eslint-config-cheminfo-typescript#9]
The rule prefer-regexp-exec prevent to use always the `match` and to force to change the syntax depending if it is 'g' or not if I understood well.

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-regexp-exec.md

In all my code I always use match and I find it more logical to apply the regexp on the string rather than the string to the regexp.

@targos  Could we make this rule a warning (or suppress it) or is there any performance of typescript issue that I don't know ?

**Comment by targos** [comment]
You can always suppress it on your projects. I don't like when there are two ways to do the same thing.

**Comment by targos** [comment]
>  I find it more logical to apply the regexp on the string rather than the string to the regexp.

I agree, and to me this is what `regexp.exec(string)` means :)

**Comment by targos** [comment]
> The rule prefer-regexp-exec prevent to use always the match and to force to change the syntax depending if it is 'g' or not if I understood well.

From my point of view, it's not that. `string.match()` has a very different behavior when the regexp is not `g`, which may confuse people (I'm sure a lot don't know about this difference). For better understanding and predictability, I prefer to always use `regexp.exec`

**Comment by lpatiny** [comment]
Question of habits I guess. because really in all my code I never used the `/abc/.exec()` syntax. 

However actually I'm never interested in the result of the match neither ... So actually I could use

`"abc".search(/c/)>-1`

I guess. Is this ok ?

Even if 

`/c/.test("abc")`

is 20% faster (on chrome, on safari it is very weird, `exec` is faster than `test` ?!)

https://jsbench.me/xbktzhkfdu/1

**Comment by targos** [comment]
> `exec` is faster than `test`

I'm a bit surprised too. In the spec, `test` is implemented using `exec`:
![image](https://user-images.githubusercontent.com/2352663/134763982-803d15f2-6e53-4217-a3cc-758b37c2ef9c.png)

**Comment by lpatiny** [comment]
I'm trying to use the `exec` syntax but still get an error. Weird.

![image](https://user-images.githubusercontent.com/1484241/134769392-e941c02f-bb77-4e09-a77b-d7855f52878b.png)

**Comment by targos** [comment]
rule was removed.
